import type { Config } from "tailwindcss";

export default {
  theme: {
    extend: {
      zIndex: {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "10": "10",
        "20": "20",
        "30": "30",
        "40": "40",
        "50": "50",
        "60": "60",
        "70": "70",
        "80": "80",
        "90": "90",
        "100": "100",

      },
      scale: {
        "200": "2.0",
        "250": "2.5",
        "300": "3.0",
        "350": "3.5",
        "400": "4.0",
        "450": "4.5",
        "500": "5.0",
        "550": "5.5",
      },
      spacing: {
        "1%": "1%",
        "2%": "2%",
        "3%": "3%",
        "4%": "4%",
        "5%": "5%",
        "6%": "6%",
        "7%": "7%",
        "8%": "8%",
        "9%": "9%",
        "10%": "10%",
        "15%": "15%",
        "20%": "20%",
        "25%": "25%",
        "30%": "30%",
        "35%": "35%",
        "40%": "40%",
        "45%": "45%",
        "50%": "50%",
      },
      fontFamily: {
        cavet: ["Cavet", "cursive"],
        anton: ["Anton", "sans-serif"],
        titillium: ["TitilliumWeb", "sans-serif"],
      },
      gridTemplateColumns: {
        "fit-8": "repeat(auto-fit, minmax(8em, 1fr))",
        "fit-10": "repeat(auto-fit, minmax(10em, 1fr))",
        "fit-12": "repeat(auto-fit, minmax(12em, 1fr))",
        "fit-14": "repeat(auto-fit, minmax(14em, 1fr))",
        "fit-16": "repeat(auto-fit, minmax(16em, 1fr))",
        "fit-18": "repeat(auto-fit, minmax(18em, 1fr))",
        "fit-20": "repeat(auto-fit, minmax(20em, 1fr))",
        "fit-22": "repeat(auto-fit, minmax(22em, 1fr))",
        "fit-24": "repeat(auto-fit, minmax(24em, 1fr))",

        "fill-8": "repeat(auto-fill, minmax(8em, 1fr))",
        "fill-10": "repeat(auto-fill, minmax(10em, 1fr))",
        "fill-12": "repeat(auto-fill, minmax(12em, 1fr))",
        "fill-14": "repeat(auto-fill, minmax(14em, 1fr))",
        "fill-16": "repeat(auto-fill, minmax(16em, 1fr))",
        "fill-18": "repeat(auto-fill, minmax(18em, 1fr))",
        "fill-20": "repeat(auto-fill, minmax(20em, 1fr))",
        "fill-22": "repeat(auto-fill, minmax(22em, 1fr))",
        "fill-24": "repeat(auto-fill, minmax(24em, 1fr))",
      },
      backgroundImage: {
        logo: "url('/logo.png')",
      }
    }
  },
  plugins: [],
  content: ["./src/**/**/*.{js,ts,jsx,tsx,mdx}"],
} satisfies Config;
